
preshots_template: ""
shots_template: "Article: \"{content}\"\nCategory: {answer}"
shots_separator: "\n"
postshots_template: "\nArticle: \"{content}\"\nCategory:"
answers_templates: 
  - "Company"
  - "Educational Institution"
  - "Artist"
  - "Athlete"
  - "Office Holder"
  - "Mean Of Transportation"
  - "Building"
  - "Natural Place"
  - "Village"
  - "Animal"
  - "Plant"
  - "Album"
  - "Film"
  - "Written Work"