
preshots_template: ""
shots_template: "Description of medical condition: \"{abstract}\"\nCondition type:"
shots_separator: "\n"
postshots_template: "\nDescription of medical condition: \"{abstract}\"\nCondition type:"
num_shots: 0
answers_templates: 
  - "Neoplasm"
  - "Digestive system disease"
  - "Nervous system disease"
  - "Cardiovascular disease"
  - "General pathological condition"