
preshots_template: ""
shots_template: "Article: \"{text}\"\nCategory: {answer}\n"
postshots_template: "Article: \"{text}\"\nCategory:"
num_shots: 0
answers_templates: 
  - "World"
  - "Sports"
  - "Business"
  - "Science and Technology"