preshots_template: "<|system|>\nProvide the correct category for the following post document provided by the user.</s>\n"
shots_template: ""
postshots_template: "<|user|>\nPost document: \"{text}\"\nCategory:</s>\n<|assistant|>\n"
num_shots: 0
answers_templates: 
    - "Atheism"
    - "Graphics"
    - "Microsoft"
    - "IBM Hardware"
    - "Mac Hardware"
    - "X Window System"
    - "Sales"
    - "Cars"
    - "Motorcycles"
    - "Baseball"
    - "Hockey"
    - "Cryptography"
    - "Electronics"
    - "Medicine"
    - "Space"
    - "Christianity"
    - "Guns"
    - "Middle East"
    - "Politics"
    - "Religion"