preshots_template: ""
shots_template: ""
postshots_template: "Instruct: Determine the category of the following post: \"{text}\"\nOutput: The post belongs to the category"
num_shots: 0
answers_templates: 
    - "Atheism"
    - "Graphics"
    - "Microsoft"
    - "IBM Hardware"
    - "Mac Hardware"
    - "X Window System"
    - "Sales"
    - "Cars"
    - "Motorcycles"
    - "Baseball"
    - "Hockey"
    - "Cryptography"
    - "Electronics"
    - "Medicine"
    - "Space"
    - "Christianity"
    - "Guns"
    - "Middle East"
    - "Politics"
    - "Religion"