
accelerator: "gpu"
devices: 1
precision: 32
quantize: null

model:
  class_name: "AffineCalibrator"
  num_classes: 2
  alpha: "vector"
  beta: True

train:
  class_name: "GradientDescentTrainer"
  loss: "cross_entropy"
  batch_size: 8
  random_state: 8293
  max_steps: 20
