
accelerator: "gpu"
devices: 1
precision: 32
quantize: null

model:
  class_name: "AffineCalibrator"
  num_classes: 2
  alpha: "matrix"
  beta: True

train:
  class_name: "GradientDescentTrainer"
  loss: "cross_entropy"
  batch_size: 8
  random_state: 8293
  max_epochs: 20
  max_ls: 40
  val_interval: 1
  checkpoint_interval: 1
