
accelerator: "gpu"
devices: 1
precision: "bf16-true"
quantize: null

model:
  class_name: "LoRALitGPTPromptClassification"
  model_name_or_path: "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"
  embedding_pooling: "last"
  num_classes: 4
  lora_r: 16
  lora_alpha: 16
  lora_dropout: 0.05
  lora_to_query: True
  lora_to_key: True
  lora_to_value: True
  lora_to_projection: True
  lora_to_mlp: True
  lora_to_head: True

train:
  class_name: "MiniBatchGDTrainer"
  batch_size: 64
  micro_batch_size: 4
  learning_rate: 0.0001
  weight_decay: 0
  max_epochs: 20
  warmup_steps: 100
  random_state: 738
  loss: cross_entropy
  val_interval: 10
  checkpoint_interval: 10
