
accelerator: "gpu"
devices: 1
precision: "bf16-true"
quantize: null

model:
  class_name: "LoRALitGPTSequenceClassification"
  model_name_or_path: "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"
  embedding_pooling: "last"
  num_classes: 4
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  lora_to_query: True
  lora_to_key: False
  lora_to_value: True
  lora_to_projection: False
  lora_to_mlp: False
  lora_to_head: False

train:
  class_name: "LoRATrainer"
  batch_size: 32
  micro_batch_size: 4
  learning_rate: 0.0001 
  weight_decay: 0
  max_epochs: 10
  tolerance: 0.000001
  random_state: 738
  loss: cross_entropy
  log_interval: 2
  val_interval: 4
