
accelerator: "gpu"
devices: 1
precision: "bf16-true"
quantize: null

model:
  class_name: "LitGPTPromptClassifier"
  model_name_or_path: "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"
  embedding_pooling: "last"

train:
  class_name: "PromptClassifierPredictor"
  val_batch_size: 8
  random_state: 8293
