
accelerator: "gpu"
devices: 1
precision: "bf16-true"
quantize: null

model:
  class_name: "LoRALitGPTPromptClassification"
  model_name_or_path: "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T-bfloat16"
  embedding_pooling: "last"
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  lora_query: True
  lora_key: True
  lora_value: True
  lora_projection: True
  lora_mlp: True
  lora_head: True

train:
  class_name: "MiniBatchGDTrainer"
  batch_size: 64
  micro_batch_size: 4
  learning_rate: 0.01
  weight_decay: 0
  max_epochs: 20
  warmup_steps: null
  random_state: 738
  loss: cross_entropy
  val_interval: 10
  checkpoint_interval: 10
