
method: "lora"
loss_fn: "cross_entropy"
optimizer: "adamw"
learning_rate: 0.0001
weight_decay: 0.0
batch_size: 1
max_epochs: 1
max_steps: -1
accumulate_grad_batches: 8
val_check_interval: 16
checkpoint_frequency: 4
random_state: 734

lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_query: True
lora_key: False
lora_value: True
lora_projection: False
lora_mlp: False
lora_head: False
