
method: "lora"
loss_fn: "cross_entropy"
optimizer: "adamw"
learning_rate: 0.0001
weight_decay: 0.0
batch_size: 1
max_epochs: 15
max_steps: -1
accumulate_grad_batches: 32
val_check_interval: 128
checkpoint_frequency: 2048 # Every n global_steps = n * batch_size * accumulate_grad_batches = 32
random_state: 734

lora_r: 64
lora_alpha: 16
lora_dropout: 0.05
lora_query: True
lora_key: True
lora_value: True
lora_projection: True
lora_mlp: True
lora_head: True
