
method: "lora"
optimizer: "adamw"
batch_size: 1
weight_decay: 0.0
learning_rate: 0.001
max_epochs: 2
max_steps: null
grad_accum_steps: 8
limit_train_batches: null
limit_val_batches: null
validation_frequency: 10
checkpoint_frequency: 100
random_state: 734
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_query: True
lora_key: False
lora_value: True
lora_projection: False
lora_mlp: False
lora_head: False