

task: "data/glue_sst2"

casting:
  class_name: "FewShotClassificationPrompt"
  preface: "Given the provided sentence, determine the sentiment expressed in it. Classify the sentiment as either 'Positive' or 'Negative'. Evaluate the overall sentiment conveyed by the sentence.\n\n"
  shots_template: null
  question: "Sentence: \"{input}\".\nLabel:"
  label2answer: ["Negative", "Positive"]
  n_shots: 0
  random_state: 728

