

task: "data/tony_zhao_dbpedia"

casting:
  class_name: "FewShotClassificationPrompt"
  preface: "Classify the article below in one of the following topic categories:\nA. Company\nB. ducational Institution\nC. Artist\nD. Athlete\nE. Office Holder\nF. Mean Of Transportation\nG. Building\nH. Natural Place\nI. Village\nJ. Animal\nK. Plant\nL. Album\nM. Film\nN. Written Work\n"
  shots_template: null
  question: "Question: What is the sentiment of the sentence \"{input}\"?\nAnswer:"
  label2answer: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N"]
  n_shots: 0
  random_state: 728

