
task: "data/tony_zhao_agnews"

casting:
  class_name: "FewShotClassificationPrompt"
  preface: ""
  shots_template: null
  question: "Classify the news articles into the categories of World, Sports, Business, and Technology.\n\nArticle: {input.article}\nAnswer:"
  label2answer: ["World", "Sports", "Business", "Technology"]
  n_shots: 0
  random_state: 728

