

task: "experiments/tony_zhao_agnews_mc/tinyllama_3T_bf16_lora_train.learning_rate=0.001_model.lora_r=8/all/"
casting:
  class_name: FeaturesSelector
  features:
    idx: idx
    target: target
    output.logits: input.logits