
task: "data/glue_mnli"

casting:
  class_name: "FewShotClassificationPrompt"
  preface: "Determine if the hypothesis is entailed, neutral, or contradicted by the premise.\n"
  shots_template: null
  question: "Premise: \"{input.premise}\".\nHypothesis: \"{input.hypothesis}\".\nWhat is the relationship between the two sentences?\nA. Entailment\nB. Neutral\nC. Contradiction\nAnswer:"
  label2answer: ["Entailment", "Neutral", "Contradiction"]
  n_shots: 0
  random_state: 728

