

task: "data/refind"

casting:
  class_name: "FewShotClassificationPrompt"
  preface: ""
  question: "Read the following sentence:\n
  \"{input.sentence}\"\n
  Identify the relationship between the entities \"{input.entity_1_token}\" and \"{input.entity_2_token}\" in the sentence above from the following options:\n
  A. No relation\n
  B. {input.entity_1_token} was formed on {input.entity_2_token}\n
  C. {input.entity_1_token} has operations in {input.entity_2_token}\n
  D. {input.entity_1_token} is a member of {input.entity_2_token}, which is an organization\n
  E. {input.entity_1_token} is an employee of {input.entity_2_token}, which is an organization\n
  F. {input.entity_1_token} is a member of {input.entity_2_token}, which is a Government Agency\n
  G. {input.entity_1_token} was acquired by {input.entity_2_token}\n
  H. {input.entity_1_token} had a loss of {input.entity_2_token}\n
  I. {input.entity_1_token} is headquartered in {input.entity_2_token}\n
  J. {input.entity_1_token} is an employee of {input.entity_2_token}, which is a University\n
  K. {input.entity_1_token} was acquired on {input.entity_2_token}\n
  L. {input.entity_1_token} has attended {input.entity_2_token}\n
  M. {input.entity_1_token} was formed in {input.entity_2_token}\n
  N. {input.entity_1_token} has a profit of {input.entity_2_token}\n
  O. {input.entity_1_token} has a cost of {input.entity_2_token}\n
  P. {input.entity_1_token} is a subsidiary of {input.entity_2_token}\n
  Q. {input.entity_1_token} has shares of {input.entity_2_token}\n
  R. {input.entity_1_token} is a founder of {input.entity_2_token}\n
  S. {input.entity_1_token} has the title {input.entity_2_token}\n
  T. {input.entity_1_token} has a revenue of {input.entity_2_token}\n
  U. {input.entity_1_token} has an agreement with {input.entity_2_token}\n
  V. {input.entity_1_token} is a member of {input.entity_2_token}, which is a University\n
  Answer:"
  shots_template: null
  label2answer: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V"]
  n_shots: 0
  random_state: 728

