
task: "data/tony_zhao_agnews"

prompt:
  class_name: FewShotClassificationPrompt
  preface: "Classify the articles below in one of the following categories:\nA. World \nB. Sports\nC.Business\nD. Science and Technology\n"
  shots_template: null
  question: "Question: What is the sentiment of the sentence \"{input}\"?\nAnswer:"
  label2answer: ["A", "B", "C", "D"]
  n_shots: 0
  random_state: 728