markersize: &markersize 6
linewidth: &linewidth 4

no_adaptation:
  label: "No Adaptation"
  color: "black"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

temp_scaling:
  label: "Temperature Scaling"
  color: "tab:blue"
  linestyle: "-"
  marker: "o"
  linewidth: *linewidth
  markersize: *markersize

dp_calibration:
  label: "Direction Preserving"
  color: "tab:orange"
  linestyle: "-"
  marker: "o"
  linewidth: *linewidth
  markersize: *markersize

vector_scaling:
  label: "Vector Scaling"
  color: "tab:purple"
  linestyle: "-"
  marker: "o"
  linewidth: *linewidth
  markersize: *markersize

bias_shift:
  label: "Bias Shift"
  color: "tab:brown"
  linestyle: "-"
  marker: "o"
  linewidth: *linewidth
  markersize: *markersize

lora_0.7:
  label: "LoRA (70% Train + 30% Val)\nwith Early Stopping"
  color: "tab:red"
  linestyle: "-"
  marker: "o"
  linewidth: *linewidth
  markersize: *markersize

lora_1.0:
  label: "LoRA (100% Train)\nwith Early Stopping"
  color: "tab:green"
  linestyle: "-"
  marker: "o"
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es:
  label: "LoRA (100% Train)\nwithout Early Stopping"
  color: "tab:green"
  linestyle: "--"
  marker: "o"
  linewidth: *linewidth
  markersize: *markersize

lora_0.7_no_es:
  label: "LoRA (p=0.7, no ES)"
  color: "green"
  linestyle: "--"
  marker: "o"
  linewidth: *linewidth
  markersize: *markersize

lora_0.7_no_es_plus_dpcal:
  label: "LoRA (p=0.7, No ES) + Direction Preserving"
  color: "tab:orange"
  linestyle: "-"
  marker: "*"
  linewidth: *linewidth
  markersize: *markersize

lora_0.7_plus_dpcal:
  label: "LoRA (p=0.7) + Direction Preserving"
  color: "tab:orange"
  linestyle: "-"
  marker: "*"
  linewidth: *linewidth
  markersize: *markersize

lora_0.7_plus_tempscaling:
  label: "LoRA (p=0.7) + Temperature Scaling"
  color: "tab:cyan"
  linestyle: "-"
  marker: "*"
  linewidth: *linewidth
  markersize: *markersize

lora_0.7_no_es_plus_tempscaling:
  label: "LoRA (p=0.7, no ES) + Temperature Scaling"
  color: "tab:cyan"
  linestyle: "--"
  marker: "x"
  linewidth: *linewidth
  markersize: *markersize

lora_0.7_no_es_plus_dpcal_trainontest:
  label: "LoRA (p=0.7, no ES) + Direction Preserving (Train on Test)"
  color: "green"
  linestyle: "--"
  marker: "x"
  linewidth: *linewidth
  markersize: *markersize

lora_0.7_no_es_plus_tempscaling_trainontest:
  label: "LoRA (p=0.7, no ES) + Temperature Scaling (Train on Test)"
  color: "tab:green"
  linestyle: "--"
  marker: "x"
  linewidth: *linewidth
  markersize: *markersize



lora_1.0_plus_dpcal:
  label: "LoRA (p=1.0) + Direction Preserving"
  color: "tab:orange"
  linestyle: "-"
  marker: "*"
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_plus_dpcal_trainontest:
  label: "LoRA (p=1.0) + Direction Preserving (Train on Test)"
  color: "tab:orange"
  linestyle: "-"
  marker: "x"
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_plus_tempscaling_trainontest:
  label: "LoRA (p=1.0) + Temperature Scaling (Train on Test)"
  color: "tab:cyan"
  linestyle: "-"
  marker: "x"
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es_plus_dpcal:
  label: "LoRA (p=1.0, no ES) + Direction Preserving"
  color: "brown"
  linestyle: "--"
  marker: "*"
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_plus_tempscaling:
  label: "LoRA (p=1.0) + Temperature Scaling"
  color: "tab:cyan"
  linestyle: "-"
  marker: "*"
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es_plus_tempscaling:
  label: "LoRA (p=1.0, no ES) + Temperature Scaling"
  color: "tab:brown"
  linestyle: "--"
  marker: "*"
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es_plus_dpcal_trainontest:
  label: "LoRA (p=1.0, no ES) + Direction Preserving (Train on Test)"
  color: "orange"
  linestyle: "--"
  marker: "x"
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es_plus_tempscaling_trainontest:
  label: "LoRA (p=1.0, no ES) + Temperature Scaling (Train on Test)"
  color: "tab:orange"
  linestyle: "--"
  marker: "x"
  linewidth: *linewidth
  markersize: *markersize
