markersize: &markersize 6
linewidth: &linewidth 4


no_adaptation:
  label: "NoA" # No Adaptation
  color: "black"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

temp_scaling:
  label: "PHC TS" # Temperature Scaling
  color: "tab:pink"
  linestyle: "-."
  marker: null
  linewidth: *linewidth
  markersize: *markersize

dp_calibration:
  label: "PHC DP" # Direction Preserving
  color: "tab:red"
  linestyle: "-."
  marker: null
  linewidth: *linewidth
  markersize: *markersize

vector_scaling:
  label: "PHC VS" # Vector Scaling
  color: "tab:cyan"
  linestyle: "-."
  marker: null
  linewidth: *linewidth
  markersize: *markersize

bias_shift:
  label: "PHC BS" # Bias Shift
  color: "tab:purple"
  linestyle: "-."
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_0.7:
  label: "SFT w/ validation" # "SFT (70% Train + 30% Val)\nw/ Early Stopping"
  # label: "SFT (70% Train + 30% Val)\nw/ Early Stopping"
  color: "tab:pink"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0:
  label: "SFT retrain" # "SFT (100% Train)\nw/ Early Stopping" 
  # label: "SFT (100% Train)\nw/ Early Stopping" 
  color: "tab:blue"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es:
  label: "SFT w/o validation" # "SFT (100% Train)\nw/o Early Stopping" 
  # label: "SFT (100% Train)\nw/o Early Stopping" 
  color: "tab:orange"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es_plus_tempscaling:
  # label: "SFT retrain + PHC TS"
  label: "Combined SFT-PHC (TS)"
  color: "tab:green"
  linestyle: "--"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es_plus_dpcal:
  # label: "SFT retrain + PHC DP"
  label: "Combined SFT-PHC (DP)"
  color: "tab:red"
  linestyle: "--"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es_plus_biasshift:
  # label: "SFT retrain + PHC BO"
  label: "Combined SFT-PHC (BO)"
  color: "tab:cyan"
  linestyle: "--"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es_plus_vectorscaling:
  # label: "SFT retrain + PHC VS"
  label: "Combined SFT-PHC (VS)"
  color: "tab:purple"
  linestyle: "--"
  marker: null
  linewidth: *linewidth
  markersize: *markersize