markersize: &markersize 6
linewidth: &linewidth 4


no_adaptation:
  label: "NoA" # No Adaptation
  color: "black"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

dirichlet_fixed_diag:
  label: "Dirichlet-FD" # Dirichlet Fixed Diagonal
  # color: "tab:green"
  # color: "#c6dbef"
  color: "#7bccc4"
  # linestyle: "-."
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

temp_scaling:
  label: "PHC-TS" # Temperature Scaling
  # color: "tab:green"
  # color: "#c6dbef"
  color: "#17becf"
  # linestyle: "-."
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

dp_calibration:
  label: "PHC-DP" # Direction Preserving
  # color: "tab:red"
  # color: "#9ecae1"
  color: "#2e86c1"
  # linestyle: "-."
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

bias_shift:
  label: "PHC-BO" # Bias Shift
  # color: "tab:cyan"
  # color: "#6baed6"
  color: "#5dade2"
  # linestyle: "-."
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

vector_scaling:
  label: "PHC-VS" # Vector Scaling
  # color: "tab:purple"
  # color: "#3182bd"
  color: "#1f77b4"
  # linestyle: "-."
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es:
  label: "SFT without regularization"
  # label: "SFT-wo-val" # "SFT (100% Train)\nw/o Early Stopping" 
  # label: "SFT (100% Train)\nw/o Early Stopping" 
  color: "#808080"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_l2-0.1_1.0:
  label: "SFT L2-reg ($\\lambda=0.1$)"
  # yellow-brown:
  color: "#CC0000"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_l2-0.01_1.0:
  label: "SFT L2-reg ($\\lambda=0.01$)"
  # yellow-brown (lighter):
  color: "#FF6666"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_0.7:
  label: "SFT Early Stopping on 70%"
  # label: "SFT-w-val" # "SFT (70% Train + 30% Val)\nw/ Early Stopping"
  # label: "SFT (70% Train + 30% Val)\nw/ Early Stopping"
  color: "#00CC00"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0:
  label: "SFT Early Stopping on 100%"
  # label: "SFT-retrain" # "SFT (100% Train)\nw/ Early Stopping" 
  # label: "SFT (100% Train)\nw/ Early Stopping" 
  color: "#66FF66"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_ls-0.1_1.0:
  label: "SFT Label Smoothing ($\\alpha=0.1$)"
  # purple-green:
  color: "#CCCC00"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_ls-0.01_1.0:
  label: "SFT Label Smoothing ($\\alpha=0.01$)"
  # purple-green (lighter):
  color: "#FFFF66"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize


lora_1.0_no_es_plus_tempscaling:
  # label: "SFT retrain + PHC TS"
  label: "SFT-wo-val + PHC-TS"
  # color: "#e74c3c"
  color: "#990099"
  # linestyle: "--"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es_plus_dpcal:
  # label: "SFT retrain + PHC DP"
  label: "SFT-wo-val + PHC-DP"
  # color: "tab:red"
  # color: "#fc9272"
  color: "#c0392b"
  # linestyle: "--"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es_plus_biasshift:
  # label: "SFT retrain + PHC BO"
  label: "SFT-wo-val + PHC-BO"
  # color: "tab:cyan"
  # color: "#fb6a4a"
  color: "#cd6155"
  # linestyle: "--"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es_plus_vectorscaling:
  # label: "SFT retrain + PHC VS"
  label: "SFT-wo-val + PHC-VS"
  # color: "tab:purple"
  # color: "#de2d26"
  color: "#d62728"
  # linestyle: "--"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize