markersize: &markersize 6
linewidth: &linewidth 4


no_adaptation:
  label: "NoA" # No Adaptation
  color: "black"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

adats_z_16:
  label: "PHC-Ada-TS" # Adaptive Temperature Scaling
  color: "#4C0099"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

dirichlet_fixed_diag:
  label: "PHC-Dirichlet-FD" # Dirichlet Fixed Diagonal
  color: "#000099"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

dirichlet_full_l2:
  label: "PHC-Dirichlet-Full-L2" # Dirichlet Fixed Diagonal
  color: "#0000FF"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

temp_scaling:
  label: "PHC-TS" # Temperature Scaling
  color: "#009999"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

dp_calibration:
  label: "PHC-DP" # Direction Preserving
  color: "#00FFFF"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

bias_shift:
  label: "PHC-BO" # Bias Shift
  color: "#00CCCC"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

vector_scaling:
  label: "PHC-VS" # Vector Scaling
  color: "#99FFFF"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es:
  label: "SFT without regularization"
  # label: "SFT-wo-val" # "SFT (100% Train)\nw/o Early Stopping" 
  # label: "SFT (100% Train)\nw/o Early Stopping" 
  color: "#808080"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_l2-0.1_1.0:
  label: "SFT L2-reg ($\\lambda=0.1$)"
  # yellow-brown:
  color: "#CC0000"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_l2-0.01_1.0:
  label: "SFT L2-reg ($\\lambda=0.01$)"
  color: "#FF6666"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_0.7:
  label: "SFT Early Stopping on 70%"
  # label: "SFT-w-val" # "SFT (70% Train + 30% Val)\nw/ Early Stopping"
  # label: "SFT (70% Train + 30% Val)\nw/ Early Stopping"
  color: "#00CC00"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0:
  label: "SFT Early Stopping on 100%"
  # label: "SFT-retrain" # "SFT (100% Train)\nw/ Early Stopping" 
  # label: "SFT (100% Train)\nw/ Early Stopping" 
  color: "#66FF66"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_ls-0.1_1.0:
  label: "SFT Label Smoothing ($\\alpha=0.1$)"
  color: "#CCCC00"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_ls-0.5_1.0:
  label: "SFT Label Smoothing ($\\alpha=0.5$)"
  color: "#FFFF00"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_ls-0.01_1.0:
  label: "SFT Label Smoothing ($\\alpha=0.01$)"
  color: "#FFFF66"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize


lora_1.0_no_es_plus_tempscaling:
  # label: "SFT retrain + PHC TS"
  label: "SFT Early Stopping on 100% + PHC-TS"
  color: "#99004C"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es_plus_dpcal:
  # label: "SFT retrain + PHC DP"
  label: "SFT Early Stopping on 100% + PHC-DP"
  color: "#FF3399"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_no_es_plus_biasshift:
  # label: "SFT retrain + PHC BO"
  label: "SFT Early Stopping on 100% + PHC-BO"
  color: "#CC0066"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_ls-0.1_plus_tempscaling:
  # label: "SFT retrain + PHC TS"
  label: "SFT Label Smoothing ($\\alpha=0.1$) + PHC-TS"
  color: "#4C0099"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_ls-0.1_plus_dpcal:
  # label: "SFT retrain + PHC DP"
  label: "SFT Label Smoothing ($\\alpha=0.1$) + PHC-DP"
  color: "#6600CC"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize

lora_1.0_ls-0.1_plus_biasshift:
  # label: "SFT retrain + PHC BO"
  label: "SFT Label Smoothing ($\\alpha=0.1$) + PHC-BO"
  color: "#7F00FF"
  linestyle: "-"
  marker: null
  linewidth: *linewidth
  markersize: *markersize
